AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Location Sharing API - SAM backend for real-time location sharing

Parameters:
  GoogleClientId:
    Type: String
    Description: Google OAuth 2.0 Client ID

  GoogleClientSecret:
    Type: String
    NoEcho: true
    Description: Google OAuth 2.0 Client Secret

  CallbackURL:
    Type: String
    Default: myapp://auth/callback
    Description: OAuth callback URL for the mobile app

  LogoutURL:
    Type: String
    Default: myapp://auth/logout
    Description: OAuth logout URL for the mobile app

  EnvironmentName:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - staging
      - prod
    Description: Deployment environment name

Globals:
  Function:
    Runtime: nodejs24.x
    Timeout: 10
    MemorySize: 256
    Architectures:
      - arm64

Resources:
  # ──────────────────────────────────────────────
  # Cognito User Pool
  # ──────────────────────────────────────────────
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub "location-sharing-${EnvironmentName}-user-pool"
      UsernameAttributes:
        - email
      AutoVerifiedAttributes:
        - email
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireUppercase: true
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: false
      Schema:
        - Name: email
          AttributeDataType: String
          Required: true
          Mutable: true
        - Name: name
          AttributeDataType: String
          Required: false
          Mutable: true
      AccountRecoverySetting:
        RecoveryMechanisms:
          - Name: verified_email
            Priority: "1"

  # ──────────────────────────────────────────────
  # Google Identity Provider
  # ──────────────────────────────────────────────
  GoogleIdentityProvider:
    Type: AWS::Cognito::UserPoolIdentityProvider
    Properties:
      UserPoolId: !Ref UserPool
      ProviderName: Google
      ProviderType: Google
      ProviderDetails:
        client_id: !Ref GoogleClientId
        client_secret: !Ref GoogleClientSecret
        authorize_scopes: "openid email profile"
      AttributeMapping:
        email: email
        name: name

  # ──────────────────────────────────────────────
  # Cognito User Pool Client (public, no secret)
  # ──────────────────────────────────────────────
  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    DependsOn: GoogleIdentityProvider
    Properties:
      ClientName: !Sub "location-sharing-${EnvironmentName}-app-client"
      UserPoolId: !Ref UserPool
      GenerateSecret: false
      ExplicitAuthFlows:
        - ALLOW_REFRESH_TOKEN_AUTH
        - ALLOW_USER_SRP_AUTH
      AllowedOAuthFlows:
        - code
      AllowedOAuthScopes:
        - openid
        - email
        - profile
      AllowedOAuthFlowsUserPoolClient: true
      SupportedIdentityProviders:
        - Google
        - COGNITO
      CallbackURLs:
        - !Ref CallbackURL
      LogoutURLs:
        - !Ref LogoutURL
      PreventUserExistenceErrors: ENABLED

  # ──────────────────────────────────────────────
  # Cognito Hosted UI Domain
  # ──────────────────────────────────────────────
  UserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: !Sub "location-sharing-${EnvironmentName}-${AWS::AccountId}"
      UserPoolId: !Ref UserPool

  # ──────────────────────────────────────────────
  # HTTP API (API Gateway v2)
  # ──────────────────────────────────────────────
  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: !Ref EnvironmentName
      Description: !Sub "Location Sharing API - ${EnvironmentName}"
      Auth:
        DefaultAuthorizer: CognitoJwtAuthorizer
        Authorizers:
          CognitoJwtAuthorizer:
            AuthorizationScopes:
              - openid
            IdentitySource: $request.header.Authorization
            JwtConfiguration:
              issuer: !Sub "https://cognito-idp.${AWS::Region}.amazonaws.com/${UserPool}"
              audience:
                - !Ref UserPoolClient

  # ──────────────────────────────────────────────
  # JWT Authorizer (externalized for cross-resource reference)
  # ──────────────────────────────────────────────
#  CognitoJwtAuthorizer:
#    Type: AWS::ApiGatewayV2::Authorizer
#    Properties:
#      ApiId: !Ref HttpApi
#      AuthorizerType: JWT
#      Name: DirectCognitoJwtAuthorizer
#      IdentitySource:
#        - $request.header.Authorization
#      JwtConfiguration:
#        Issuer: !Sub "https://cognito-idp.${AWS::Region}.amazonaws.com/${UserPool}"
#        Audience:
#          - !Ref UserPoolClient

  # ──────────────────────────────────────────────
  # API to SQS Direct Integration
  # ──────────────────────────────────────────────
  ApiToSqsRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: apigateway.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: ApiToSqsPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: sqs:SendMessage
                Resource: !GetAtt LocationQueue.Arn

#  LocationQueueIntegration:
#    Type: AWS::ApiGatewayV2::Integration
#    Properties:
#      ApiId: !Ref HttpApi
#      IntegrationType: AWS_PROXY
#      IntegrationSubtype: SQS-SendMessage
#      CredentialsArn: !GetAtt ApiToSqsRole.Arn
#      PayloadFormatVersion: "1.0"
#      RequestParameters:
#        QueueUrl: !Ref LocationQueue
#        MessageBody: $request.body
#        MessageGroupId: $context.authorizer.jwt.claims.sub
#        MessageDeduplicationId: $context.requestId

#  PostLocationRoute:
#    Type: AWS::ApiGatewayV2::Route
#    Properties:
#      ApiId: !Ref HttpApi
#      RouteKey: "POST /location"
#      Target: !Sub "integrations/${LocationQueueIntegration}"
#      AuthorizationType: JWT
#      AuthorizerId: !Ref CognitoJwtAuthorizer

  # ──────────────────────────────────────────────
  # Lambda Functions
  # ──────────────────────────────────────────────
  HealthFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2022"
        Sourcemap: true
        EntryPoints:
          - src/handlers/health.ts
    Properties:
      FunctionName: !Sub "location-sharing-${EnvironmentName}-health"
      Handler: health.handler
      CodeUri: .
      Environment:
        Variables:
          ENVIRONMENT: !Ref EnvironmentName
      Events:
        GetHealth:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /health
            Method: GET

  GetFriendsFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2022"
        Sourcemap: true
        EntryPoints:
          - src/handlers/get-friends.ts
    Properties:
      FunctionName: !Sub "location-sharing-${EnvironmentName}-get-friends"
      Handler: get-friends.handler
      CodeUri: .
      Environment:
        Variables:
          ENVIRONMENT: !Ref EnvironmentName
      Events:
        GetFriends:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /friends
            Method: GET

  ProcessLocationFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2022"
        Sourcemap: true
        EntryPoints:
          - src/handlers/process-location.ts
    Properties:
      FunctionName: !Sub "location-sharing-${EnvironmentName}-process-location"
      Handler: process-location.handler
      CodeUri: .
      Environment:
        Variables:
          ENVIRONMENT: !Ref EnvironmentName
          LOCATION_TABLE_NAME: !Ref LocationDataTable
      Policies:
        - DynamoDBWritePolicy:
            TableName: !Ref LocationDataTable
      Events:
        ProcessLocation:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /location
            Method: POST

  GetProfileFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2022"
        Sourcemap: true
        EntryPoints:
          - src/handlers/get-profile.ts
    Properties:
      FunctionName: !Sub "location-sharing-${EnvironmentName}-get-profile"
      Handler: get-profile.handler
      CodeUri: .
      Environment:
        Variables:
          ENVIRONMENT: !Ref EnvironmentName
          LOCATION_TABLE_NAME: !Ref LocationDataTable
          GOOGLE_CONFIG_PARAMETER_NAME: !Sub "/location-sharing-app/${EnvironmentName}/google-config"
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref LocationDataTable
        - SSMParameterReadPolicy:
            ParameterName: !Sub "location-sharing-app/${EnvironmentName}/google-config"
      Events:
        GetProfile:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /profile
            Method: GET

  # ──────────────────────────────────────────────
  # SQS Queue
  # ──────────────────────────────────────────────
  LocationQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "location-sharing-${EnvironmentName}-location-queue.fifo"
      FifoQueue: true
      ContentBasedDeduplication: true

  # ──────────────────────────────────────────────
  # DynamoDB Tables
  # ──────────────────────────────────────────────
  LocationDataTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: LocationData
      PrimaryKey:
        Name: userId
        Type: String


Outputs:
  UserPoolId:
    Description: Cognito User Pool ID
    Value: !Ref UserPool

  UserPoolClientId:
    Description: Cognito User Pool Client ID
    Value: !Ref UserPoolClient

  CognitoDomain:
    Description: Cognito Hosted UI Domain URL
    Value: !Sub "https://location-sharing-${EnvironmentName}-${AWS::AccountId}.auth.${AWS::Region}.amazoncognito.com"

  JwksIssuerUrl:
    Description: JWKS Issuer URL for JWT validation
    Value: !Sub "https://cognito-idp.${AWS::Region}.amazonaws.com/${UserPool}"

  HttpApiEndpoint:
    Description: HTTP API endpoint URL
    Value: !Sub "https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com/${EnvironmentName}"
