AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Location Sharing API - SAM backend for real-time location sharing

Parameters:
  GoogleClientId:
    Type: String
    Description: Google OAuth 2.0 Client ID

  GoogleClientSecret:
    Type: String
    NoEcho: true
    Description: Google OAuth 2.0 Client Secret

  CallbackURL:
    Type: String
    Default: myapp://auth/callback
    Description: OAuth callback URL for the mobile app

  LogoutURL:
    Type: String
    Default: myapp://auth/logout
    Description: OAuth logout URL for the mobile app

  EnvironmentName:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - staging
      - prod
    Description: Deployment environment name

Globals:
  Function:
    Runtime: nodejs24.x
    Timeout: 10
    MemorySize: 256
    Architectures:
      - arm64

Resources:
  # ──────────────────────────────────────────────
  # Cognito User Pool
  # ──────────────────────────────────────────────
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub "location-sharing-${EnvironmentName}-user-pool"
      UsernameAttributes:
        - email
      AutoVerifiedAttributes:
        - email
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireUppercase: true
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: false
      Schema:
        - Name: email
          AttributeDataType: String
          Required: true
          Mutable: true
        - Name: name
          AttributeDataType: String
          Required: false
          Mutable: true
      AccountRecoverySetting:
        RecoveryMechanisms:
          - Name: verified_email
            Priority: "1"

  # ──────────────────────────────────────────────
  # Google Identity Provider
  # ──────────────────────────────────────────────
  GoogleIdentityProvider:
    Type: AWS::Cognito::UserPoolIdentityProvider
    Properties:
      UserPoolId: !Ref UserPool
      ProviderName: Google
      ProviderType: Google
      ProviderDetails:
        client_id: !Ref GoogleClientId
        client_secret: !Ref GoogleClientSecret
        authorize_scopes: "openid email profile"
      AttributeMapping:
        email: email
        name: name

  # ──────────────────────────────────────────────
  # Cognito User Pool Client (public, no secret)
  # ──────────────────────────────────────────────
  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    DependsOn: GoogleIdentityProvider
    Properties:
      ClientName: !Sub "location-sharing-${EnvironmentName}-app-client"
      UserPoolId: !Ref UserPool
      GenerateSecret: false
      ExplicitAuthFlows:
        - ALLOW_REFRESH_TOKEN_AUTH
        - ALLOW_USER_SRP_AUTH
      AllowedOAuthFlows:
        - code
      AllowedOAuthScopes:
        - openid
        - email
        - profile
      AllowedOAuthFlowsUserPoolClient: true
      SupportedIdentityProviders:
        - Google
        - COGNITO
      CallbackURLs:
        - !Ref CallbackURL
      LogoutURLs:
        - !Ref LogoutURL
      PreventUserExistenceErrors: ENABLED

  # ──────────────────────────────────────────────
  # Cognito Hosted UI Domain
  # ──────────────────────────────────────────────
  UserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: !Sub "location-sharing-${EnvironmentName}-${AWS::AccountId}"
      UserPoolId: !Ref UserPool

  # ──────────────────────────────────────────────
  # HTTP API (API Gateway v2)
  # ──────────────────────────────────────────────
  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: !Ref EnvironmentName
      Description: !Sub "Location Sharing API - ${EnvironmentName}"
      Auth:
        DefaultAuthorizer: CognitoJwtAuthorizer
        Authorizers:
          CognitoJwtAuthorizer:
            AuthorizationScopes:
              - openid
            IdentitySource: $request.header.Authorization
            JwtConfiguration:
              issuer: !Sub "https://cognito-idp.${AWS::Region}.amazonaws.com/${UserPool}"
              audience:
                - !Ref UserPoolClient

  # ──────────────────────────────────────────────
  # Lambda Functions
  # ──────────────────────────────────────────────
  HealthFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2022"
        Sourcemap: true
        EntryPoints:
          - src/handlers/health.ts
    Properties:
      FunctionName: !Sub "location-sharing-${EnvironmentName}-health"
      Handler: health.handler
      CodeUri: .
      Environment:
        Variables:
          ENVIRONMENT: !Ref EnvironmentName
      Events:
        GetHealth:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /health
            Method: GET

  GetFriendsFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2022"
        Sourcemap: true
        EntryPoints:
          - src/handlers/get-friends.ts
    Properties:
      FunctionName: !Sub "location-sharing-${EnvironmentName}-get-friends"
      Handler: get-friends.handler
      CodeUri: .
      Environment:
        Variables:
          ENVIRONMENT: !Ref EnvironmentName
      Events:
        GetFriends:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /friends
            Method: GET

Outputs:
  UserPoolId:
    Description: Cognito User Pool ID
    Value: !Ref UserPool

  UserPoolClientId:
    Description: Cognito User Pool Client ID
    Value: !Ref UserPoolClient

  CognitoDomain:
    Description: Cognito Hosted UI Domain URL
    Value: !Sub "https://location-sharing-${EnvironmentName}-${AWS::AccountId}.auth.${AWS::Region}.amazoncognito.com"

  JwksIssuerUrl:
    Description: JWKS Issuer URL for JWT validation
    Value: !Sub "https://cognito-idp.${AWS::Region}.amazonaws.com/${UserPool}"

  HttpApiEndpoint:
    Description: HTTP API endpoint URL
    Value: !Sub "https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com/${EnvironmentName}"
